


const loc = {
  ru: {
    App: {
      login: 'Вход',
      logoutHint: 'Выйти',
      newJobHint: 'Создать новую вакансию'
    },
    home: {
      searchHint: 'Поиск по полям название, автор, город, основной текст',
      searchValSym: 'некорректная строка поиска',
      searchBtn: 'Поиск',
      city: 'Город',
      sal: 'Зарплата',
      curr: 'Валюта',
      currDefault: [
        {label: "все", value: 'idc'},
        {label: "$", value: '$'},
        {label: "манат", value: 'm'},],
      exp: 'Опыт',
      //jtyp: 'Занятость',
      jcat: 'Профессия',
      applyBtn: 'Применить'
    },
    companyPage: {
      categoriesHeader: 'Сферы деятельности компании',
      descHeader: 'Описание',
      publishedJobsCountLabel: 'Размещено вакансий: ',
      registrationDate: 'Зарегистрирована: ',
    },
    entProfile: {
      navPublishedLabel: 'Вакансии',
      navResponsesLabel: 'Отклики',
      navAboutLabel: 'О компании',
      navSettingsLabel: 'Настройки',
      publishedHeader: 'Опубликованные вакансии',
    },
    reg: {
      loginLabel: 'Вход',
      regLabel: 'Регистрация',
      loginEmailLabel: 'Email',
      loginPWLabel: 'Пароль',
      rmeLabel: 'Запомнить меня',
      frgtPWLabel: 'Забыл пароль?',
      enterBtn: 'Войти',
      radioSub: 'Специалист',
      radioCom: 'Компания',
      companyLabel: 'Компания',
      agencyLabel: 'Кадровое агенство',
      nameLabel: 'Имя',
      surnameLabel: 'Фамилия',
      regConfirmPWLabel: 'Повтор пароля',
      rulesStart: 'Я соглашаюсь с',
      rulesLink: 'правилами использования сервиса',
      rulesEnd: ', а также с передачей и обработкой моих данных в TEST.com. Я подтверждаю своё совершеннолетие и ответственность за размещение объявления.',
      regBtn: 'Регистрация',
      alreadyAuthedMessage: 'Авторизован',
      loginValiMail0: 'Введите email',
      loginValiMailFormat: 'Неправильный формат адреса',
      loginValiPW0: 'Введите пароль',
      loginValiPWFormat: 'Кол-во символов от 5 до 25',
      loginSuccess: 'Вход осуществлен',
      loginError1: 'Не существующий Email или не правильный пароль',
      loginError2: 'Такого пользователя не существует, либо неверный пароль',
      loginError3: 'Не удалось выполнить вход',
      regValiRules: 'Ознакомтесь с правилами',
      regValiPWC0: 'Подтвердите пароль',
      regValiPWCDiff: 'Пароли не совпадают',
      regValiPWChar: 'Минимум 1 английская буква',
      regValiPWMax: 'Максимум 25 символов',
      regValiPWMin: 'Минимум 6 символов',
      regValiPW0: 'Введите пароль',
      compValiFormat: 'Неправильный формат названия',
      compValiMax: 'Максимальная длина 60 символов',
      compValiMin: 'Минимальная длина 3 символа',
      compVali0: 'Введите название',
      surnameValiFormat: 'Неправильный формат фамилии',
      surnameValiMax: 'Максимальная длина 35 символов',
      surnameValiMin: 'Минимальная длина 3 символа',
      surnameVali0: 'Введите фамилию',
      nameValiFormat: 'Неправильный формат имени',
      nameValiMax: 'Максимальная длина 35 символов',
      nameValiMin: 'Минимальная длина 3 символа',
      nameVali0: 'Введите имя',
      regSuccess: 'Регистрация удалась',
      regAllFields: 'Заполните все поля',
      regError1: 'Email или пароль не зарегестрированы',
      regError2: 'Такой email уже существует в базе данных',
      regError3: 'Регистрация не удалась, ошибки на сервере',
    },
    addJob: {
      pTypeNewLabel: 'Создать новую вакансию',
      pTypeEditLabel: 'Редактирование вакансии',
      titleLabel: 'Название вакансии',
      xlsBtn: 'Публикация вакансий XLS',
      titleValidationRequired: '* Обязательное поле',
      titleValidationMin: 'Минимум 2 символа',
      titleValidationMax: 'Максимум 75 символов',
      titleValidationSymbols: 'Используются запрещенные символы',
      salaryLabel: 'Зарплата',
      salaryMinPH: 'От',
      salaryValidationRange: 'От 0 до 99999',
      salaryMaxPH: 'До',
      salaryValidationEnter: 'Укажите зп',
      manat: 'манат',
      dollars: '$',
      salaryCB1Hint: 'По итогам собеседования',
      contactsLabel: 'Ваши контакты',
      emailPH: 'Email',
      emailValidationLength: 'Максимум 40 символов',
      emailValidationFormat: 'Неправильный формат',
      emailValidationEnter: 'Укажите Email или Телефон',
      telPH: 'Телефон',
      telValidationLengthMax: 'Максимум 15 символов',
      telValidationLengthMin: 'Минимум 5 символов',
      telValidationFormat: 'Неправильный формат',
      jcatLabel: 'Профессия',
      cityLabel: 'Город',
      cityValidationLength: 'Максимум 70 символов',
      cityValidationFormat: 'Только буквы',
      descLabel: 'Описание',
      descValidation2000: '(2000 символов максимум)',
      moreLabel: 'Дополнительно',
      expLabel: 'Опыт',
      jobTypeLabel: 'Тип занятости',
      ageLabel: 'Возраст',
      genericFrom: 'От',
      genericTo: 'До',
      genericEnterNumber: 'Введите число',
      genericFrom18: 'От 18',
      genericTooMuch: 'Слишком много',
      labelSchedule: 'График работы',
      genericWholeNumber:'Целое число',
      genericPositiveNumber: 'Положительное',
      generic24Max: '24 макс',
      schedulePH: 'Режим',
      scheduleValidationLengthMax: 'Максимум 10 символов',
      scheduleValidationFormat: 'Неправильный формат',
      eduLabel: 'Образование',
      eduValidationLengthMax: '20 символов макс',
      eduValidationFormat: 'Только буквы',
      eduTooltip: 'Например: высшее, среднее, высшее/среднее и т.д',
      langsLabel: 'Языки',
      sendJobBtnLabelNew: 'Разместить вакансию',
      sendJobBtnLabelUpdate: 'Отправить изменения',
      sendJobSuccess1: 'Вакансия ',
      sendJobSuccess2: ' успешно добавлена',
      sendJobSuccess1x: 'Вакансия ',
      sendJobSuccess2x: ' успешно изменена',
      btnAddOneMore: 'Добавить еще одну',
      sendJobError1: 'Ошибка на сервере, вакансия не добавлена',
      unauthorized: 'Авторизируйтесь, для возможности загрузки вакансий',
      cityOptions: ["Ашхабад", "Дашогуз", "Мары", "Туркменабад", "Туркменбаши"],
      jcats: [{label: "Не имеет значения", value: 0}, 
        {label: "Администрация", value: 1},
        {label: "Юристы", value: 2},
        {label: "Нефть и газ", value: 3},
        {label: "Инженер", value: 4},
        {label: "Образование", value: 5},
        {label: "Продажи", value: 6},
        {label: "Производство", value: 7},
        {label: "Строительство", value: 8},
        {label: "Недвижимость", value: 9},
        {label: "Логистика", value: 10},
        {label: "Туризм, гостиницы, рестораны", value: 11},
        {label: "Информационные технологии", value: 12},
        {label: "Медицина", value: 13},
        {label: "Безопасность", value: 14}
      ],
      expOpts: [
        {label: "Не имеет значения", value: -1},
        {label: "Без опыта", value: 0},
        {label: "от 1 до 3 лет", value: 2}, 
        {label: "от 3 до 5 лет", value: 4},
        {label: "от 5 лет", value: 6}
      ],
      jtypeOptions: [
        {label: "Постоянная", value: 'c'},
        {label: "Временная", value: 'v'}
      ],
      langOptions: ["Туркменский", "Русский", "Английский", "Китайский", "Немецкий", "Французкий"],
      cityList: ["Ашхабад", "Дашогуз", "Мары", "Туркменабад", "Туркменбаши"],
      scheduleList: ["5/2", "6/1", "2/2", "3/2", "3/1", "15/15"],
      currDefault: {label: 'манат', value: 'm'},
    }
  },
  tm: {
    App: {
      login: 'Вход',
      logoutHint: 'Выйти',
      newJobHint: 'Создать новую вакансию'
    },
    home: {
      searchHint: 'Поиск по полям название, автор, город, основной текст',
      searchValSym: 'некорректная строка поиска',
      searchBtn: 'Поиск',
      city: 'Город',
      sal: 'Зарплата',
      curr: 'Валюта',
      currDefault: [
        {label: "все", value: 'idc'},
        {label: "$", value: '$'},
        {label: "манат", value: 'm'},],
      exp: 'Опыт',
      //jtyp: 'Занятость',
      jcat: 'Профессия',
      applyBtn: 'Применить'
    },
    companyPage: {
      categoriesHeader: 'Сферы деятельности компании',
      descHeader: 'Описание',
      publishedJobsCountLabel: 'Размещено вакансий: ',
      registrationDate: 'Зарегистрирована: ',
    },
    entProfile: {
      navPublishedLabel: 'Вакансии',
      navResponsesLabel: 'Отклики',
      navAboutLabel: 'О компании',
      navSettingsLabel: 'Настройки',
      publishedHeader: 'Опубликованные вакансии',
    },
    addJob: {
      pTypeNewLabel: 'Täze wezipe döretmek',
      pTypeEditLabel: 'Wezipäni üýtgetmek',
      titleLabel: 'Wezipäniň ady',
      xlsBtn: 'Birnäçe wezipäni birden goşmak',
      titleValidationRequired: '* Hökmany ýer',
      titleValidationMin: 'Azydan 2 nyşan',
      titleValidationMax: 'Iň käni 75 nyşan',
      titleValidationSymbols: 'Gadagan nyşanlar ulanylýar',
      salaryLabel: 'Aýlyk',
      salaryMinPH: 'От',
      salaryValidationRange: 'От 0 до 99999',
      salaryMaxPH: 'До',
      salaryValidationEnter: 'Aýlygy görkeziň',
      manat: 'manat',
      dollars: '$',
      salaryCB1Hint: 'Söhbetdeşlik esasynda',
      contactsLabel: 'Siziň kontaktlaryňyz',
      emailPH: 'Email',
      emailValidationLength: 'Iň käni 75 nyşan',
      emailValidationFormat: 'Ýalňyş format',
      emailValidationEnter: 'Email-ňyzy görkeziň ýa-da telefonyňyzy',
      telPH: 'Telefon',
      telValidationLengthMax: 'Iň käni 15 nyşan',
      telValidationLengthMin: 'Azydan 5 nyşan',
      telValidationFormat: 'Ýalňyş format',
      jcatLabel: 'Hünär',
      cityLabel: 'Şäher',
      cityValidationLength: 'Iň käni 70 nyşan',
      cityValidationFormat: 'Diňe harplar',
      descLabel: 'Düşündiriş',
      descValidation2000: '(Iň käni 2000 nyşan)',
      moreLabel: 'Goşmaça',
      expLabel: 'Tejribe',
      jobTypeLabel: 'Işliligiň görnüşi',
      ageLabel: 'Ýaşy',
      genericFrom: 'От',
      genericTo: 'До',
      genericEnterNumber: 'San ýazyň',
      genericFrom18: 'От 18',
      genericTooMuch: 'Gaty kän',
      labelSchedule: 'Işiň grafigi',
      genericWholeNumber:'Bitin san',
      genericPositiveNumber: 'Положительное',
      generic24Max: '24 maks',
      schedulePH: 'Režim',
      scheduleValidationLengthMax: 'Iň käni 10 nyşan',
      scheduleValidationFormat: 'Ýalňyş format',
      eduLabel: 'Bilimi',
      eduValidationLengthMax: 'Iň käni 20 nyşan',
      eduValidationFormat: 'Diňe harplar',
      eduTooltip: 'Mysal üçin: ýokary, orta we ş.m.',
      langsLabel: 'Diller',
      sendJobBtnLabelNew: 'Wezipäni goşmak',
      sendJobBtnLabelUpdate: 'Üýtgetmeleri ugratmak',
      sendJobSuccess1: 'Wezipe ',
      sendJobSuccess2: ' goşuldy',
      sendJobSuccess1x: 'Wezipe ',
      sendJobSuccess2x: ' üýtgedildi',
      btnAddOneMore: 'Ýene birini goşmak',
      sendJobError1: 'Serwerda ýalňyşlyk, wezipe goşulmady',
      unauthorized: 'Wezipäni goşmak üçin saýta giriň',
      cityOptions: ["Aşgabat", "Daşoguz", "Mary", "Türkmenabat", "Türkmenbaşy"],
      jcats: [{label: "Tapawudy ýok", value: 0}, 
        {label: "Administrasiýa", value: 1},
        {label: "Ýuristler", value: 2},
        {label: "Nebit we gaz", value: 3},
        {label: "Inžener", value: 4},
        {label: "Bilim", value: 5},
        {label: "Söwda", value: 6},
        {label: "Önümçilik", value: 7},
        {label: "Gurluşyk", value: 8},
        {label: "Gozgalmaýan emläk", value: 9},
        {label: "Logistika", value: 10},
        {label: "Turizm, myhmanhanalar, restoranlar", value: 11},
        {label: "Informasion tehnologiýalar", value: 12},
        {label: "Saglyk", value: 13},
        {label: "Howpsuzlyk", value: 14}
      ],
      expOpts: [
        {label: "Tapawudy ýok", value: -1},
        {label: "Tejribe hökman däl", value: 0},
        {label: "от 1 до 3 лет", value: 2}, 
        {label: "от 3 до 5 лет", value: 4},
        {label: "от 5 лет", value: 6}
      ],
      jtypeOptions: [
        {label: "Hemişelik", value: 'c'},
        {label: "Wagtlaýyn", value: 'v'}
      ],
      langOptions: ["Türkmen dili", "Rus dili", "Iňlis dili", "Hytaý dili", "Nemes dili", "Fransuz dili"],
      cityList: ["Aşgabat", "Daşoguz", "Mary", "Türkmenabat", "Türkmenbaşy"],
      scheduleList: ["5/2", "6/1", "2/2", "3/2", "3/1", "15/15"],
      currDefault: {label: 'manat', value: 'm'},
    }
  },
  en: {
    App: {
      login: 'Вход',
      logoutHint: 'Выйти',
      newJobHint: 'Создать новую вакансию'
    },
    home: {
      searchHint: 'Поиск по полям название, автор, город, основной текст',
      searchValSym: 'некорректная строка поиска',
      searchBtn: 'Поиск',
      city: 'Город',
      sal: 'Зарплата',
      curr: 'Валюта',
      currDefault: [
        {label: "все", value: 'idc'},
        {label: "$", value: '$'},
        {label: "манат", value: 'm'},],
      exp: 'Опыт',
      //jtyp: 'Занятость',
      jcat: 'Профессия',
      applyBtn: 'Применить'
    },
    companyPage: {
      categoriesHeader: 'Сферы деятельности компании',
      descHeader: 'Описание',
      publishedJobsCountLabel: 'Размещено вакансий: ',
      registrationDate: 'Зарегистрирована: ',
    },
    entProfile: {
      navPublishedLabel: 'Вакансии',
      navResponsesLabel: 'Отклики',
      navAboutLabel: 'О компании',
      navSettingsLabel: 'Настройки',
      publishedHeader: 'Опубликованные вакансии',
    },
    addJob: {
      pTypeNewLabel: 'Создать новую вакансию',
      pTypeEditLabel: 'Редактирование вакансии',
      titleLabel: 'Название вакансии',
      xlsBtn: 'Публикация вакансий XLS',
      titleValidationRequired: '* Обязательное поле',
      titleValidationMin: 'Минимум 2 символа',
      titleValidationMax: 'Максимум 75 символов',
      titleValidationSymbols: 'Используются запрещенные символы',
      salaryLabel: 'Зарплата',
      salaryMinPH: 'От',
      salaryValidationRange: 'От 0 до 99999',
      salaryMaxPH: 'До',
      salaryValidationEnter: 'Укажите зп',
      manat: 'манат',
      dollars: '$',
      salaryCB1Hint: 'По итогам собеседования',
      contactsLabel: 'Ваши контакты',
      emailPH: 'Email',
      emailValidationLength: 'Максимум 40 символов',
      emailValidationFormat: 'Неправильный формат',
      emailValidationEnter: 'Укажите Email или Телефон',
      telPH: 'Телефон',
      telValidationLengthMax: 'Максимум 15 символов',
      telValidationLengthMin: 'Минимум 5 символов',
      telValidationFormat: 'Неправильный формат',
      jcatLabel: 'Профессия',
      cityLabel: 'Город',
      cityValidationLength: 'Максимум 70 символов',
      cityValidationFormat: 'Только буквы',
      descLabel: 'Описание',
      descValidation2000: '(2000 символов максимум)',
      moreLabel: 'Дополнительно',
      expLabel: 'Опыт',
      jobTypeLabel: 'Тип занятости',
      ageLabel: 'Возраст',
      genericFrom: 'От',
      genericTo: 'До',
      genericEnterNumber: 'Введите число',
      genericFrom18: 'От 18',
      genericTooMuch: 'Слишком много',
      labelSchedule: 'График работы',
      genericWholeNumber:'Целое число',
      genericPositiveNumber: 'Положительное',
      generic24Max: '24 макс',
      schedulePH: 'Режим',
      scheduleValidationLengthMax: 'Максимум 10 символов',
      scheduleValidationFormat: 'Неправильный формат',
      eduLabel: 'Образование',
      eduValidationLengthMax: '20 символов макс',
      eduValidationFormat: 'Только буквы',
      eduTooltip: 'Например: высшее, среднее, высшее/среднее и т.д',
      langsLabel: 'Языки',
      sendJobBtnLabelNew: 'Разместить вакансию',
      sendJobBtnLabelUpdate: 'Отправить изменения',
      sendJobSuccess1: 'Вакансия ',
      sendJobSuccess2: ' успешно добавлена',
      sendJobSuccess1x: 'Вакансия ',
      sendJobSuccess2x: ' успешно изменена',
      btnAddOneMore: 'Добавить еще одну',
      sendJobError1: 'Ошибка на сервере, вакансия не добавлена',
      unauthorized: 'Авторизируйтесь, для возможности загрузки вакансий',
      cityOptions: ["Ашхабад", "Дашогуз", "Мары", "Туркменабад", "Туркменбаши"],
      jcats: [{label: "Не имеет значения", value: 0}, 
        {label: "АдминистрацияXX", value: 1},
        {label: "Юристы", value: 2},
        {label: "Нефть и газ", value: 3},
        {label: "Инженер", value: 4},
        {label: "Образование", value: 5},
        {label: "Продажи", value: 6},
        {label: "Производство", value: 7},
        {label: "Строительство", value: 8},
        {label: "Недвижимость", value: 9},
        {label: "Логистика", value: 10},
        {label: "Туризм, гостиницы, рестораны", value: 11},
        {label: "Информационные технологии", value: 12},
        {label: "Медицина", value: 13},
        {label: "Безопасность", value: 14}
      ],
      expOpts: [
        {label: "Не имеет значения", value: -1},
        {label: "Без опыта", value: 0},
        {label: "от 1 до 3 лет", value: 2}, 
        {label: "от 3 до 5 лет", value: 4},
        {label: "от 5 лет", value: 6}
      ],
      jtypeOptions: [
        {label: "Постоянная", value: 'c'},
        {label: "Временная", value: 'v'}
      ],
      langOptions: ["Туркменский", "Русский", "Английский", "Китайский", "Немецкий", "Французкий"],
      cityList: ["Ашхабад", "Дашогуз", "Мары", "Туркменабад", "Туркменбаши"],
      scheduleList: ["5/2", "6/1", "2/2", "3/2", "3/1", "15/15"],
      currDefault: {label: 'манат', value: 'm'},
    }
  },
}

module.exports = {
  loc
}