const loc = {
  ru: {
    fb: {
      topic: 'Тема',
      yourname: 'Ваше имя',
      hyphenMail: '* Email',
      mailValReq: 'Обязательное поле',
      mailValFormat: 'Некорректный формат адреса',
      textLabel: 'Пожелания',
      btnSend: 'Отправить',
      btnSendMore: 'Отправить еще',
      toMain: 'На главную',
      messageSuccess: 'Успешно отправлено',
      messageError: 'Ошибка на сервере',
      reqMail: 'Поле email обязательное',
      fbSuccess: 'Фидбэк отправлен',
      fbError: 'Ошибка на сервере',
    },
    companyPage: {
      categoriesHeader: 'Сферы деятельности компании',
      descHeader: 'Описание',
      publishedJobsCountLabel: 'Размещено вакансий: ',
      registrationDate: 'Зарегистрирована: ',
    },
    jobPage: {
      jobClosed: 'Вакансия закрыта',
      reason: 'причина',
      sendCV: 'Подать резюме',
      cvAlreadySent: 'Резюме уже подано',
      reqs: 'Требования',
      none: 'Не указаны',
      expNone: 'Без опыта.',
      exp1_3: 'Опыт: от 1 до 3 лет.',
      exp3_5: 'Опыт: от 3 до 5 лет.',
      exp5_: 'Опыт: от 5 лет.',
      ageLabel: 'Возраст:',
      from: 'от',
      to: 'до',
      years: 'лет',
      eduLabel: 'Образование:',
      langsLabel: 'Языки:',
      conds: 'Условия работы',
      salLabel: 'Оклад:',
      from2: 'с',
      schedule: 'График работы:',
      jTypeLabel: 'Вакансия',
      jTypePermanent: 'постоянная',
      jTypeTemporary: 'временная',
      desc: 'Описание',
      contacts: 'Контакты',
      publishedDate: 'Дата публикации:',
      salaryNone: 'по итогам собеседования',
      jobNotPublishedYet: 'Вакансия будет видна в общем списке после проверки модератором',
    },
    App: {
      login: 'Вход',
      logoutHint: 'Выйти',
      newJobHint: 'Создать вакансию',
      logoTooltip: 'Главная',
      myProfile: 'Мой кабинет',
      fbBtnLabel: 'Написать нам',
      jcats: [
        {label: "Не имеет значения", value: 0},
        {label: "Бух учет, финансы", value: 19},
        {label: "Гос служба", value: 1},
        {label: "Дизайн, полиграфия", value: 14},
        {label: "ИТ, Интернет", value: 4},
        {label: "Красота, фитнес, спорт", value: 12},
        {label: "Логистика, склад", value: 10},
        {label: "Маркетинг, реклама", value: 13},
        {label: "Медицина, Фармация, Ветеринария", value: 9},
        {label: "Недвижимость, риэлтерские услуги", value: 3},
        {label: "Нефть и Газ", value: 5},
        {label: "Образование, репетиторство", value: 6},
        {label: "Производство, агропром", value: 7},
        {label: "Рестораны, питание", value: 8},
        {label: "Строительство", value: 11},
        {label: "Торговля", value: 2},
        {label: "Транспорт, автосервис", value: 15},
        {label: "Туризм, гостиницы", value: 16},
        {label: "Юриспруденция", value: 17},
        {label: "HR, кадры", value: 18},
      ],
      expOpts: [
        {label: "Не имеет значения", value: -1},
        {label: "Без опыта", value: 0},
        {label: "от 1 до 3 лет", value: 2}, 
        {label: "от 3 до 5 лет", value: 4},
        {label: "от 5 лет", value: 6}
      ],
      jtypeOptions: [
        {label: "Постоянная", value: 'c'},
        {label: "Временная", value: 'v'}
      ],
      curOpts: [
        {label: 'манат', value: 'm'},      
        {label: '$', value: '$'},
      ],
      cityList: ["Ашхабад", "Дашогуз", "Мары", "Туркменабад", "Туркменбаши"],
      firstCVNote: 'Сначала загрузите резюме!',
      onlyRegisteredCV: 'Подавать резюме могут <span style="color: red">зарегистрированные</span> пользователи',
      currencyDic: {
        '$': '$',
        'm': 'манат',
      },
    },
    filters: {
      searchHint: 'Поиск по полям название, автор, город, основной текст',
      searchValSym: 'некорректная строка поиска',
      searchBtn: 'Поиск',
      city: 'Город',
      sal: 'Зарплата',
      curr: 'Валюта',
      currDefault: [
        {label: "все", value: 'idc'},
        {label: "$", value: '$'},
        {label: "манат", value: 'm'},],
      exp: 'Опыт',
      jcat: 'Профессия',
      applyBtn: 'Применить',
      expFilters: [
        {label: "Не имеет значения", value: 'idc'}, 
        {label: "Без опыта", value: '0'},
        {label: "от 1 до 3 лет", value: '1-3'}, 
        {label: "от 3 до 5 лет", value: '3-5'},
        {label: "от 5 лет", value: '5'}
      ],
      salFilters: [
        {label: "Не имеет значения", value: 'idc'}, 
        {label: "от 0 до 1000", value: '0-1'}, 
        {label: "от 1000 до 3000", value: '1-3'}, 
        {label: "от 3000", value: '3'},
      ],
      cities: ["Не имеет значения", "Ашхабад", "Дашогуз", "Мары", "Туркменабад", "Туркменбаши"],
    },
    jobs: {
      sortOpts: [
        {label: 'По дате ↓', value: 'new'},
        {label: 'По зп ↓', value: 'saldesc'},
        {label: 'По зп ↑', value: 'salasc'}
      ],
      dateOpts: [
        {label: 'За месяц', value: 'mon'},
        {label: 'За неделю', value: 'wee'},
        {label: 'За сутки', value: 'day'}
      ],
      perpageOpts: [
        {label: '25 на стр', value: '25'},
        {label: '50 на стр', value: '50'},
        {label: '100 на стр', value: '100'}
      ],
      
    },
    jc: {
      salaryNone: 'По итогам собеседования',
      expEmpty: 'Опыт не указан.',
      expNone: 'Без опыта.',
      exp1_3: 'Опыт: от 1 до 3 лет.',
      exp3_5: 'Опыт: от 3 до 5 лет.',
      exp5_: 'Опыт: от 5 лет.',
      sendCVLabel: 'Подать резюме',
      tooltipSent: 'Отправлено',
      tooltipSeen: 'Просмотрено',
      tooltipNotseen: 'Не просмотрено',
      contactsLabel: 'Контакты',
      today: 'Сегодня',
      yesterday: 'Вчера',
      daysAgo: 'дня назад',
    },
    reg: {
      loginLabel: 'Вход',
      regLabel: 'Регистрация',
      loginEmailLabel: 'Email',
      loginPWLabel: 'Пароль',
      rmeLabel: 'Запомнить меня',
      frgtPWLabel: 'Забыл пароль?',
      enterBtn: 'Войти',
      radioSub: 'Специалист',
      radioCom: 'Компания',
      companyLabel: 'Компания',
      agencyLabel: 'Кадровое агенство',
      nameLabel: 'Имя',
      surnameLabel: 'Фамилия',
      regConfirmPWLabel: 'Повтор пароля',
      rulesStart: 'Я соглашаюсь с',
      rulesLink: 'правилами использования сервиса',
      rulesEnd: ', а также с передачей и обработкой моих данных в TEST.com. Я подтверждаю своё совершеннолетие и ответственность за размещение объявления.',
      regBtn: 'Регистрация',
      alreadyAuthedMessage: 'Авторизован',
      loginValiMail0: 'Введите email',
      loginValiMailFormat: 'Неправильный формат адреса',
      loginValiPW0: 'Введите пароль',
      loginValiPWFormat: 'Кол-во символов от 5 до 25',
      loginSuccess: 'Вход осуществлен',
      loginError1: 'Не существующий Email или не правильный пароль',
      loginError2: 'Такого пользователя не существует, либо неверный пароль',
      loginError3: 'Не удалось выполнить вход',
      regValiRules: 'Ознакомтесь с правилами',
      regValiPWC0: 'Подтвердите пароль',
      regValiPWCDiff: 'Пароли не совпадают',
      regValiPWChar: 'Минимум 1 английская буква',
      regValiPWMax: 'Максимум 25 символов',
      regValiPWMin: 'Минимум 6 символов',
      regValiPW0: 'Введите пароль',
      compValiFormat: 'Неправильный формат названия',
      compValiMax: 'Максимальная длина 60 символов',
      compValiMin: 'Минимальная длина 3 символа',
      compVali0: 'Введите название',
      surnameValiFormat: 'Неправильный формат фамилии',
      surnameValiMax: 'Максимальная длина 35 символов',
      surnameValiMin: 'Минимальная длина 3 символа',
      surnameVali0: 'Введите фамилию',
      nameValiFormat: 'Неправильный формат имени',
      nameValiMax: 'Максимальная длина 35 символов',
      nameValiMin: 'Минимальная длина 3 символа',
      nameVali0: 'Введите имя',
      regSuccess: 'Регистрация удалась',
      regAllFields: 'Заполните все поля',
      regError1: 'Email или пароль не зарегестрированы',
      regError2: 'Такой email уже существует в базе данных',
      regError3: 'Регистрация не удалась, ошибки на сервере',
    },
    addJob: {
      pTypeNewLabel: 'Создать новую вакансию',
      pTypeEditLabel: 'Редактирование вакансии',
      titleLabel: 'Название вакансии',
      xlsBtn: 'Публикация вакансий XLS',
      titleValidationRequired: '* Обязательное поле',
      titleValidationMin: 'Минимум 2 символа',
      titleValidationMax: 'Максимум 75 символов',
      titleValidationSymbols: 'Используются запрещенные символы',
      salaryLabel: 'Зарплата',
      salaryMinPH: 'От',
      salaryValidationRange: 'От 0 до 99999',
      salaryMaxPH: 'До',
      salaryValidationEnter: 'Укажите зп',
      manat: 'манат',
      dollars: '$',
      salaryCB1Hint: 'По итогам собеседования',
      contactsLabel: 'Ваши контакты',
      emailPH: 'Email',
      emailValidationLength: 'Максимум 40 символов',
      emailValidationFormat: 'Неправильный формат',
      emailValidationEnter: 'Укажите Email или Телефон',
      telPH: 'Телефон',
      telValidationLengthMax: 'Максимум 15 символов',
      telValidationLengthMin: 'Минимум 5 символов',
      telValidationFormat: 'Неправильный формат',
      jcatLabel: 'Профессия',
      cityLabel: 'Город',
      cityValidationLength: 'Максимум 70 символов',
      cityValidationFormat: 'Только буквы',
      descLabel: 'Описание',
      descValidation2000: '(2000 символов максимум)',
      moreLabel: 'Дополнительно',
      expLabel: 'Опыт',
      jobTypeLabel: 'Тип занятости',
      ageLabel: 'Возраст',
      genericFrom: 'От',
      genericTo: 'До',
      genericEnterNumber: 'Введите число',
      genericFrom18: 'От 18',
      genericTooMuch: 'Слишком много',
      labelSchedule: 'График работы',
      genericWholeNumber:'Целое число',
      genericPositiveNumber: 'Положительное',
      generic24Max: '24 макс',
      schedulePH: 'Режим',
      scheduleValidationLengthMax: 'Максимум 10 символов',
      scheduleValidationFormat: 'Неправильный формат',
      eduLabel: 'Образование',
      eduValidationLengthMax: '20 символов макс',
      eduValidationFormat: 'Только буквы',
      eduTooltip: 'Например: высшее, среднее, высшее/среднее и т.д',
      langsLabel: 'Языки',
      sendJobBtnLabelNew: 'Разместить вакансию',
      sendJobBtnLabelUpdate: 'Отправить изменения',
      sendJobSuccess1: 'Вакансия ',
      sendJobSuccess2: ' успешно добавлена',
      sendJobSuccess1x: 'Вакансия ',
      sendJobSuccess2x: ' успешно изменена',
      btnAddOneMore: 'Добавить еще одну',
      sendJobError1: 'Ошибка на сервере, вакансия не добавлена',
      unauthorized: 'Авторизируйтесь, для возможности загрузки вакансий',
      cityOptions: ["Ашхабад", "Дашогуз", "Мары", "Туркменабад", "Туркменбаши"],
      langOptions: ["Туркменский", "Русский", "Английский", "Китайский", "Немецкий", "Французкий"],
      scheduleList: ["5/2", "6/1", "2/2", "3/2", "3/1", "15/15"],
      currDefault: {label: 'манат', value: 'm'},
    },
    entProfile: {
      navPublishedLabel: 'Вакансии',
      navResponsesLabel: 'Отклики',
      navAboutLabel: 'О компании',
      navSettingsLabel: 'Настройки',
      publishedHeader: 'Опубликованные вакансии',
      cvSent: 'Подано:',
      cvSeen: 'Просмотрено:',
      cvNotSeen: 'Просмотрено: нет',
      cname: 'Название компании',
      dragLogo: 'Загрузка логотипа компании (Перетяните)',
      sitePH: 'Сайт',
      catPH: 'Сфера деятельности',
      descPH: 'Описание',
      sendChanges: 'Отправить изменения',
      settingsLabel: 'Компания',
      emailLabel: 'Email',
      oldPWLabel: 'Старый пароль',
      newPWLabel: 'Новый пароль',
      changeSettingsBtn: 'Изменить',
      companyDomains: ["Автомобильный бизнес", "Гостиницы, рестораны, общепит, кейтеринг", "Государственные организации", "Добывающая отрасль", "ЖКХ", "Информационные технологии, системная интеграция, интернет", "Искусство, культура", "Лесная промышленность, деревообработка", "Медицина, фармацевтика, аптеки", "Металлургия, металлообработка", "Нефть и газ", "Образовательные учреждения", "Общественная деятельность, партии, благотворительность, НКО", "Перевозки, логистика, склад, ВЭД", "Продукты питания", "Промышленное оборудование, техника, станки и комплектующие", "Розничная торговля", "СМИ, маркетинг, реклама, BTL, PR, дизайн", "Сельское хозяйство", "Строительство, эксплуатация, проектирование", "Недвижимость", "Телекоммуникации, связь", "Товары народного потребления (непищевые)", "Тяжелое машиностроение", "Управление многопрофильными активами", "Услуги для бизнеса", "Услуги для населения", "Финансовый сектор", "Химическое производство, удобрения", "Электроника, приборостроение, бытовая техника, компьютеры и оргтехника", "Энергетика"],
      pwChanged: 'Пароль изменен',
      pwWrongData: 'Неправильные данные',
      dataChanged: 'Данные изменены',
      dataError: 'Ошибка',
      picLoaded: 'Изображение загружено',
      picTooBig: 'Картинка больше 400кб'
    },
    jobsStats: {
      title: 'Название',
      views: 'Всего просмотров',
      uniqViews: 'Уникальных просмотров',
      published: 'Опубликована',
      change: 'Изменить',
      close: 'Закрыть',
      delete: 'Удалить',
      closed: 'Закрыта',
      none: 'Нет ни одной вакансии',
      publishedHint: 'Публикуется после проверки модератором',
      yes: 'Да',
      no: 'Нет',
    }
  },
  tm: {
    fb: {
      topic: 'Tema',
      yourname: 'Siziň adyňyz',
      hyphenMail: '* Email',
      mailValReq: 'Hökmany ýer',
      mailValFormat: 'Adresyň ýalňyş formady',
      textLabel: 'Teklip',
      btnSend: 'Ugratmak',
      btnSendMore: 'Ýene ugratmak',
      toMain: 'Esasy sahypa',
      messageSuccess: 'Üstünlikli ugradyldy',
      messageError: 'Serwerde ýalňyş',
      reqMail: 'Hökmany ýer',
      fbSuccess: 'Sorag ugradyldy',
      fbError: 'Serwerde ýalňyşlyk',
    },
    companyPage: {
      categoriesHeader: 'Kompaniýanyň iş ugurlary',
      descHeader: 'Düşündiriş',
      publishedJobsCountLabel: 'Wezipe goşuldy: ',
      registrationDate: 'Registrasiýa bolan: ',
    },
    jobPage: {
      jobClosed: 'Wezipe ýapyk',
      reason: 'sebäbi',
      sendCV: 'Rezýume ugratmak',
      cvAlreadySent: 'Rezýume eýýäm ugradyldy',
      reqs: 'Talaplar',
      none: 'Görkezilmedik',
      expNone: 'Tejribe hölman däl.',
      exp1_3: 'Tejribe: 1 den 3 ýyla.',
      exp3_5: 'Tejribe: 3 den 5 ýyla.',
      exp5_: 'Tejribe: 5 ýyldan köp.',
      ageLabel: 'Ýaşy:',
      from: 'от',
      to: 'до',
      years: 'лет',
      eduLabel: 'Bilimi:',
      langsLabel: 'Diller:',
      conds: 'Işiň şertleri',
      salLabel: 'Aýlyk:',
      from2: 'с',
      schedule: 'Işiň grafigi:',
      jTypeLabel: 'Wezipe',
      jTypePermanent: 'hemişelik',
      jTypeTemporary: 'wagtlaýyn',
      desc: 'Düşündiriş',
      contacts: 'Kontaktlar',
      publishedDate: 'Döredilen wagty:',
      salaryNone: 'söhbetdeşlik esasynda',
      
    },
    App: {
      login: 'Girmek',
      logoutHint: 'Çykmak',
      newJobHint: 'Wezipe döretmek',
      logoTooltip: 'Esasy sahypa',
      myProfile: 'Kabinet',
      fbBtnLabel: 'Bize ýazyň',
      jcats: [
        {label: "Tapawudy ýok", value: 0},
        {label: "Buhuçet, maliýe", value: 19},
        {label: "Döwlet işi", value: 1},
        {label: "Dizaýn, çaphanaçylyk", value: 14},
        {label: "IT, Internet", value: 4},
        {label: "Owadanlyk, fitnes, sport", value: 12},
        {label: "Logistika, ammar", value: 10},
        {label: "Marketing, mahabat", value: 13},
        {label: "Medisina, Farmasewtika, Weterinariýa", value: 9},
        {label: "Gozgalmaýan emläk, rieltor hyzmatlary", value: 3},
        {label: "Nebit we Gaz", value: 5},
        {label: "Bilim, repetitorçylyk", value: 6},
        {label: "Önümçilik, agrosenagat", value: 7},
        {label: "Restoranlar, iýmit", value: 8},
        {label: "Gurluşyk", value: 11},
        {label: "Söwda", value: 2},
        {label: "Transport, awtohyzmatlary", value: 15},
        {label: "Syýahatçylyk, myhmanhanalar", value: 16},
        {label: "Hukuk", value: 17},
        {label: "HR, kadr işi", value: 18},
      ],
      expOpts: [
        {label: "Tapawudy ýok", value: -1},
        {label: "Tejribe hökman däl", value: 0},
        {label: "1 den 3 ýyla", value: 2}, 
        {label: "3 den 5 ýyla", value: 4},
        {label: "5 ýyldan köp", value: 6}
      ],
      jtypeOptions: [
        {label: "Hemişelik", value: 'c'},
        {label: "Wagtlaýyn", value: 'v'}
      ],
      curOpts: [
        {label: 'manat', value: 'm'},      
        {label: '$', value: '$'},
      ],
      cityList: ["Aşgabat", "Daşoguz", "Mary", "Türkmenabat", "Türkmenbaşy"],
      firstCVNote: 'Ilki rezýumeňizi ýerleşdiriň!',
      onlyRegisteredCV: 'Rezýumeni diňe <span style="color: red">registrasiýa</span> bolan ulanyjylar ugradyp bilýär',
      currencyDic: {
        '$': '$',
        'm': 'manat',
      },
    },
    filters: {
      searchHint: 'Atlar boýunça, awtor, şäher, esasy tekst boýunça gözleg',
      searchValSym: 'poiskyň ýalňyş setiri',
      searchBtn: 'Gözle',
      city: 'Şäher',
      sal: 'Aýlyk',
      curr: 'Walýuta',
      currDefault: [
        {label: "ähli", value: 'idc'},
        {label: "manat", value: 'm'},
        {label: "$", value: '$'},
      ],
      exp: 'Tejribe',
      jcat: 'Hünär',
      applyBtn: 'Ulanmak',
      expFilters: [
        {label: "Tapawudy ýok", value: 'idc'}, 
        {label: "Tejribe hökman däl", value: '0'},
        {label: "1 den 3 ýyla", value: '1-3'}, 
        {label: "3 den 5 ýyla", value: '3-5'},
        {label: "5 ýyldan köp", value: '5'}
      ],
      salFilters: [
        {label: "Tapawudy ýok", value: 'idc'}, 
        {label: "0 dan 1000 çenli", value: '0-1'}, 
        {label: "1000 dan 3000 çenli", value: '1-3'}, 
        {label: "3000 den köp", value: '3'},
      ],
      cities: ["Tapawudy ýok", "Aşgabat", "Daşoguz", "Mary", "Türkmenabat", "Türkmenbaşy"],
    },
    jobs: {
      sortOpts: [
        {label: 'Güni ↓', value: 'new'},
        {label: 'Aýlygyň azalmasy', value: 'saldesc'},
        {label: 'Aýlygyň köpelmesi', value: 'salasc'}
      ],
      dateOpts: [
        {label: 'Bir aýyňky', value: 'mon'},
        {label: 'Bir hepdäňki', value: 'wee'},
        {label: 'Bir günüňki', value: 'day'}
      ],
      perpageOpts: [
        {label: '25 sany', value: '25'},
        {label: '50 sany', value: '50'},
        {label: '100 sany', value: '100'}
      ],
      
    },
    jc: {
      salaryNone: 'Söhbetdeşlik esasynda',
      expEmpty: 'Tejribe görkezilmedik.',
      expNone: 'Tejribe hökman däl.',
      exp1_3: 'Tejribe: 1 den 3 ýyla.',
      exp3_5: 'Tejribe: 3 den 5 ýyla.',
      exp5_: 'Tejribe: 5 ýyldan köp.',
      sendCVLabel: 'Rezýumeni ugrat',
      tooltipSent: 'Ugradyldy',
      tooltipSeen: 'Seredildi',
      tooltipNotseen: 'Seredilenok',
      contactsLabel: 'Kontaktlar',
      today: 'Bu gün',
      yesterday: 'Düýn',
      daysAgo: 'gün mundan öň',
    },
    reg: {
      loginLabel: 'Giriş',
      regLabel: 'Registrasiýa',
      loginEmailLabel: 'Email',
      loginPWLabel: 'Parol',
      rmeLabel: 'Ýatda sakla',
      frgtPWLabel: 'Parol ýatdan çykdymy?',
      enterBtn: 'Giriş',
      radioSub: 'Işgär',
      radioCom: 'Edara',
      companyLabel: 'Edara',
      agencyLabel: 'Kadr agentligi',
      nameLabel: 'Ady',
      surnameLabel: 'Familiýasy',
      regConfirmPWLabel: 'Paroli gaýtala',
      rulesStart: 'Men razy',
      rulesLink: 'serwisyň ulanyş düzgünleri bilen',
      rulesEnd: ', hem-de öz maglumatlarymy TEST.com saýtyna ugratmaga we ulanmaga razylygymy berýärin. Men kämillik ýaşyma ýetendigimi subut edýärin we saýtda ýerleşdirjek bildirişlerim üçin jogap kärçilik çekýärin.',
      regBtn: 'Registrasiýa',
      alreadyAuthedMessage: 'Awtorizasiýa boldy',
      loginValiMail0: 'Email ýazyň',
      loginValiMailFormat: 'Adres ýalňyş formatda',
      loginValiPW0: 'Paroly ýazyň',
      loginValiPWFormat: 'Nyşanlaryň sany 5-den 25-e çenli',
      loginSuccess: 'Giriş üstünlikli geçdi',
      loginError1: 'Email ýalňyş ýa-da parol',
      loginError2: 'Olar ýaly ulanyjy ýok, ýa-da ýalňyş parol',
      loginError3: 'Giriş amala aşyrylmady',
      regValiRules: 'Düzgünler (şertler) bilen tanyşyň',
      regValiPWC0: 'Parolyňyzy gaýtalaň',
      regValiPWCDiff: 'Parollar gabat gelenok',
      regValiPWChar: 'Azyndan 1 iňlis harp',
      regValiPWMax: 'Iň käni 25 nyşan',
      regValiPWMin: 'Azyndan 6 nyşan',
      regValiPW0: 'Paroly ýazyň',
      compValiFormat: 'Adyň ýalňyş formady',
      compValiMax: 'Iň käni 60 nyşan',
      compValiMin: 'Azyndan 3 nyşan',
      compVali0: 'Ady ýazyň',
      surnameValiFormat: 'Familiýanyň ýalňyş formady',
      surnameValiMax: 'Iň käni 35 nyşan',
      surnameValiMin: 'Azyndan 3 nyşan',
      surnameVali0: 'Familiýany ýazyň',
      nameValiFormat: 'Adyň ýalňyş formady',
      nameValiMax: 'Iň käni 35 nyşan',
      nameValiMin: 'Azyndan 3 nyşan',
      nameVali0: 'Ady ýazyň',
      regSuccess: 'Registrasiýa üstünlikli geçdi',
      regAllFields: 'Hemme ýerleri doldyryň',
      regError1: 'Email ýa-da parol registrasiýa bolmadyk',
      regError2: 'Bu email öň registrasiýa edilen',
      regError3: 'Registrasiýa üstünlikli bolmady, serwerde ýalňyşlyk',
    },
    addJob: {
      pTypeNewLabel: 'Täze wezipe döretmek',
      pTypeEditLabel: 'Wezipäni üýtgetmek',
      titleLabel: 'Wezipäniň ady',
      xlsBtn: 'Birnäçe wezipäni birden goşmak',
      titleValidationRequired: '* Hökmany ýer',
      titleValidationMin: 'Azydan 2 nyşan',
      titleValidationMax: 'Iň käni 75 nyşan',
      titleValidationSymbols: 'Gadagan nyşanlar ulanylýar',
      salaryLabel: 'Aýlyk',
      salaryMinPH: 'den',
      salaryValidationRange: '0 dan 99999 çenli',
      salaryMaxPH: 'çenli',
      salaryValidationEnter: 'Aýlygy görkeziň',
      manat: 'manat',
      dollars: '$',
      salaryCB1Hint: 'Söhbetdeşlik esasynda',
      contactsLabel: 'Siziň kontaktlaryňyz',
      emailPH: 'Email',
      emailValidationLength: 'Iň käni 75 nyşan',
      emailValidationFormat: 'Ýalňyş format',
      emailValidationEnter: 'Email-ňyzy görkeziň ýa-da telefonyňyzy',
      telPH: 'Telefon',
      telValidationLengthMax: 'Iň käni 15 nyşan',
      telValidationLengthMin: 'Azydan 5 nyşan',
      telValidationFormat: 'Ýalňyş format',
      jcatLabel: 'Hünär',
      cityLabel: 'Şäher',
      cityValidationLength: 'Iň käni 70 nyşan',
      cityValidationFormat: 'Diňe harplar',
      descLabel: 'Düşündiriş',
      descValidation2000: '(Iň käni 2000 nyşan)',
      moreLabel: 'Goşmaça',
      expLabel: 'Tejribe',
      jobTypeLabel: 'Işliligiň görnüşi',
      ageLabel: 'Ýaşy',
      genericFrom: 'den',
      genericTo: 'çenli',
      genericEnterNumber: 'San ýazyň',
      genericFrom18: '18 den',
      genericTooMuch: 'Gaty kän',
      labelSchedule: 'Işiň grafigi',
      genericWholeNumber:'Bitin san',
      genericPositiveNumber: 'Oňaýly',
      generic24Max: '24 maks',
      schedulePH: 'Režim',
      scheduleValidationLengthMax: 'Iň käni 10 nyşan',
      scheduleValidationFormat: 'Ýalňyş format',
      eduLabel: 'Bilimi',
      eduValidationLengthMax: 'Iň käni 20 nyşan',
      eduValidationFormat: 'Diňe harplar',
      eduTooltip: 'Mysal üçin: ýokary, orta we ş.m.',
      langsLabel: 'Diller',
      sendJobBtnLabelNew: 'Wezipäni goşmak',
      sendJobBtnLabelUpdate: 'Üýtgetmeleri ugratmak',
      sendJobSuccess1: 'Wezipe ',
      sendJobSuccess2: ' goşuldy',
      sendJobSuccess1x: 'Wezipe ',
      sendJobSuccess2x: ' üýtgedildi',
      btnAddOneMore: 'Ýene birini goşmak',
      sendJobError1: 'Serwerda ýalňyşlyk, wezipe goşulmady',
      unauthorized: 'Wezipäni goşmak üçin saýta giriň',
      cityOptions: ["Aşgabat", "Daşoguz", "Mary", "Türkmenabat", "Türkmenbaşy"],
      // jcats: [{label: "Tapawudy ýok", value: 0}, 
      //   {label: "Administrasiýa", value: 1},
      //   {label: "Ýuristler", value: 2},
      //   {label: "Nebit we gaz", value: 3},
      //   {label: "Inžener", value: 4},
      //   {label: "Bilim", value: 5},
      //   {label: "Söwda", value: 6},
      //   {label: "Önümçilik", value: 7},
      //   {label: "Gurluşyk", value: 8},
      //   {label: "Gozgalmaýan emläk", value: 9},
      //   {label: "Logistika", value: 10},
      //   {label: "Turizm, myhmanhanalar, restoranlar", value: 11},
      //   {label: "Informasion tehnologiýalar", value: 12},
      //   {label: "Saglyk", value: 13},
      //   {label: "Howpsuzlyk", value: 14}
      // ],
      expOpts: [
        {label: "Tapawudy ýok", value: -1},
        {label: "Tejribe hökman däl", value: 0},
        {label: "1 den 3 ýyla", value: 2}, 
        {label: "3 den 5 ýyla", value: 4},
        {label: "5 ýyldan köp", value: 6}
      ],
      jtypeOptions: [
        {label: "Hemişelik", value: 'c'},
        {label: "Wagtlaýyn", value: 'v'}
      ],
      langOptions: ["Türkmen dili", "Rus dili", "Iňlis dili", "Hytaý dili", "Nemes dili", "Fransuz dili"],
      cityList: ["Aşgabat", "Daşoguz", "Mary", "Türkmenabat", "Türkmenbaşy"],
      scheduleList: ["5/2", "6/1", "2/2", "3/2", "3/1", "15/15"],
      currDefault: {label: 'manat', value: 'm'},
    },
  },

}

module.exports = {
  loc
}